# Build stage
FROM denoland/deno:debian-2.4.5 AS builder

# Setup Environment
WORKDIR /app
ENV NODE_ENV=production

# Copy necessary files for build
COPY . .

# Install dependencies and build
RUN deno task install && deno task build

# Generate search index
RUN deno task pagefind

# Final stage
FROM denoland/deno:alpine-2.4.5
WORKDIR /app

# Copy built files
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/public ./public
COPY --from=builder /app/deno_prod.json ./deno.json

# Expose port
EXPOSE 8085

# Start the server with logging
CMD ["task", "service"]