
services:
  blog_dev:
    restart: always # 跟系統服務一起重啟
    image: node:lts-alpine
    ports:
      - 4321:4321
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ./:/app
