FROM denoland/deno:2.2.6

# Setup Environment
WORKDIR /app
ENV NODE_ENV=production

# Copy Project Source Code  
COPY . .

# Building Static Site
RUN deno task install && deno task build 

# Find Site Page
RUN deno task pagefind && ls -l dist/pagefind
RUN mkdir -p public/pagefind
RUN cp -r dist/pagefind/* public/pagefind/

# Service Start 
CMD ["deno", "task", "serve"]

# Listens Serve  Port
EXPOSE 8085
