# Build stage
FROM denoland/deno:debian-2.9.7 AS builder

# Install system dependencies
RUN apt-get update && apt-get install -y \
    python3 \
    make \
    npm \
    g++ \
    && rm -rf /var/lib/apt/lists/*

# Setup Environment
WORKDIR /app
ENV NODE_ENV=production
ENV DENO_DIR=/deno-dir

COPY . .

RUN mkdir -p /app/.npm && \
    npm config set cache /app/.npm --global
RUN deno task install && deno task build && deno task pagefind && deno run -A scripts/precompress.ts
RUN cp deno.lock deno.runtime.lock \
    && deno cache --config deno_prod.json --lock=deno.runtime.lock ./dist/server.ts

# Final stage
FROM denoland/deno:alpine-2.9.7
WORKDIR /app

# Copy built files
ENV DENO_DIR=/deno-dir
COPY --from=builder /deno-dir /deno-dir
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/deno_prod.json ./deno.json
COPY --from=builder /app/deno.runtime.lock ./deno.runtime.lock

# Expose port
EXPOSE 8085

# Switch to non-root user for security
USER deno

# Start the server with logging
CMD ["task", "service"]
