name: Deploy deno.dev Service
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  # GitHub Actions Runner Images: https://github.com/actions/runner-images/tree/main
  deploy:
    name: Deploy to Deno Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write #  Auth with Deno Deploy
      contents: read # Clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install step
        run: "deno task install"

      - name: Build step - 1
        run: "deno task build"

      - name: Pagefind step
        run: "deno task pagefind"

      - name: Build step - 2
        run: "deno task build"

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "neko-0xff-blog"
          entrypoint: "dist/server/entry.mjs"
          root: "dist"
